# Generated by Django 4.2.2 on 2023-09-21 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coiffuresapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, default='', max_length=1000, verbose_name='ID client')),
                ('montant', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('payer', models.BooleanField(default=False, verbose_name='Payé')),
                ('checkout_url', models.CharField(blank=True, default='', max_length=1000)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.client')),
                ('coiffure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.coiffuresgaleries')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'paiements',
            },
        ),
    ]
