# Generated by Django 4.2.2 on 2023-09-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientPaie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
