# Generated by Django 4.2.2 on 2023-09-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categorisCoiffures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cat', models.CharField(max_length=60, unique=True, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='coiffuresGaleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_coi', models.CharField(max_length=60, unique=True, verbose_name='Coiffure')),
                ('desc_coi', models.TextField(max_length=255, verbose_name='Description')),
                ('prix_coi', models.CharField(max_length=12, verbose_name='Prix')),
                ('img_coi', models.ImageField(upload_to='media', verbose_name='Image')),
                ('slugs', models.SlugField(blank=True, default='', max_length=500, null=True)),
                ('created_coi', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('update_coi', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorieCoiffures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.categoriscoiffures', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Coiffure',
                'verbose_name_plural': 'Coiffures',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_con', models.CharField(max_length=35, verbose_name='Nom contact')),
                ('email_con', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('message_con', models.TextField(max_length=255, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='commentaireCoiffure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_coi', models.TextField(max_length=255, null=True, verbose_name='Commentaire')),
                ('coiffure_id_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.coiffuresgaleries', verbose_name='Coiffures')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cl', models.CharField(max_length=25, unique=True, verbose_name='Nom')),
                ('email_cl', models.EmailField(blank=True, max_length=40, unique=True, verbose_name='Email')),
                ('telephone_cl', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages='Ce numéro existe déjà !', max_length=128, region=None, unique=True)),
                ('adresse_cl', models.CharField(max_length=60, verbose_name='Adresse')),
                ('time_coi', models.TimeField(null=True, verbose_name='Heure')),
                ('days_coi', models.DateField(null=True, verbose_name='Jour pour la coiffure')),
                ('coifGa_id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.coiffuresgaleries', verbose_name='Coiffure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
