# Generated by Django 4.2.2 on 2023-09-22 17:25

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0002_alter_coiffuresgaleries_img_coi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coiffuresgaleries',
            name='img_coi',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[350, 350], upload_to='media'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.BooleanField(blank=True, null=True)),
                ('mobile_money', models.BooleanField(blank=True, null=True, verbose_name='Mobile Money')),
                ('stripe', models.BooleanField(blank=True, null=True, verbose_name='Stripe')),
                ('paypal', models.BooleanField(blank=True, null=True, verbose_name='Paypal')),
                ('especes', models.BooleanField(blank=True, null=True, verbose_name='Espèces')),
                ('coiffure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.coiffuresgaleries', verbose_name='Coiffure')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='paie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.payment', verbose_name='Paiement'),
        ),
    ]
