# Generated by Django 4.2.2 on 2023-09-22 18:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0003_alter_coiffuresgaleries_img_coi_payment_client_paie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone_cl',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages='Ce numéro existe déjà !', max_length=12, region=None, unique=True),
        ),
    ]
