# Generated by Django 4.2.2 on 2023-09-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0005_remove_client_coifga_id_client_remove_client_paie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='montant',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='client',
            name='secret',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='ID client'),
        ),
    ]
