# Generated by Django 4.2.2 on 2023-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0006_client_montant_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone_cl',
            field=models.CharField(blank=True, error_messages='Ce numéro existe déjà !', max_length=12, unique=True),
        ),
    ]
