# Generated by Django 4.2.2 on 2023-09-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0007_alter_client_telephone_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='montant',
            field=models.PositiveIntegerField(default=0, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone_cl',
            field=models.CharField(blank=True, error_messages='Ce numéro existe déjà !', max_length=12, unique=True, verbose_name='Téléphone'),
        ),
    ]
