# Generated by Django 4.2.2 on 2023-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0009_alter_client_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse_cl',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse'),
        ),
    ]
