# Generated by Django 4.2.2 on 2023-09-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0011_client_coiffure_client_especes_client_mobile_money_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='especes',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Espèces'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile_money',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Mobile Money'),
        ),
        migrations.AlterField(
            model_name='client',
            name='paypal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Paypal'),
        ),
        migrations.AlterField(
            model_name='client',
            name='stripe',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Stripe'),
        ),
    ]
