# Generated by Django 4.2.2 on 2023-09-24 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0013_paie_remove_client_especes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.paie', verbose_name='Paiement'),
        ),
    ]
