# Generated by Django 4.2.2 on 2023-09-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0015_remove_paie_especes_remove_paie_mobile_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coiffuresgaleries',
            name='paie',
        ),
        migrations.AlterField(
            model_name='client',
            name='paie',
            field=models.CharField(max_length=60, null=True, verbose_name='Paiement'),
        ),
    ]
