# Generated by Django 4.2.2 on 2023-09-25 10:35

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0017_typecoiffure_categoriscoiffures_img_couverture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='media/slider')),
                ('titre', models.CharField(max_length=255, null=True, verbose_name='Titre')),
                ('paragraphe', models.CharField(max_length=60, null=True, verbose_name='Paragraphe')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
