# Generated by Django 4.2.2 on 2023-09-27 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coiffuresapp', '0018_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriscoiffures',
            name='coiffurePour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coiffuresapp.typecoiffure', verbose_name='Coiffure pour'),
        ),
    ]
